[book]
authors = ["Robin KÃ¥veland"]
language = "en"
multilingual = false
src = "src"
title = "Eugene Documentation"

[output.html]
site-url = "/eugene/"
git-repository-url = "https://github.com/kaaveland/eugene"
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 1
